name:  pixi
version: 0.1.0
description: >
  Port of the pixi.js library for 2D graphics using WebGL where available and the
  canvas where not.
author: Dan Parnham <dan@teadriven.me.uk>
homepage: http://github.com/emergent-design/pixi.dart

dependencies:
  browser: ">=0.9.0 < 1.0.0"
  js: ">=0.2.0 < 0.3.0"

environment:
  sdk: ">=0.8.10+6 <2.0.0"

dev_dependencies:
  unittest: any
