name:  pixi
version: 0.0.3
description: >
  Port of the pixi.js library for 2D graphics using WebGL where available and the
  canvas where not.
author: Dan Parnham <dan@teadriven.me.uk>
homepage: http://github.com/emergent-design/pixi.dart

dependencies:
  browser: any
  js: any

dev_dependencies:
  unittest: any
