name:  pixi
version: 0.0.1
description: >
  Port of the pixi.js library for 2D graphics using WebGL where available and the
  canvas where not.
author: Dan Parnham <dan@teadriven.me.uk>
homepage: http://github.com/parnham/pixi.dart

dependencies:
  browser: ">=0.8.7 <0.8.8"
  js: ">=0.0.26 <0.0.27"

dev_dependencies:
  unittest: any
