name:  pixi
version: 4.6.2-0
description: >
  An interop wrapper around the pixijs library.
author: Dan Parnham <dan@emergent-design.co.uk>
homepage: http://github.com/emergent-design/pixi.dart

dependencies:
  js: ^0.6.1

environment:
  sdk: '>=1.24.3 <2.0.0'

dev_dependencies:
  browser: ^0.10.0

dev_environment:
